### ISSUE TITLE
[support] socks5 or http username and password authentication

### ISSUE THREAD

**Issue by passwa11** [AbelChe/rabbithole#1]
if local proxy file include authentication of socks5 or http:
```
http://admin:pass@1.1.1.1:10008
socks5://admin:pass@2.2.2.2:1080
```

**Comment by AbelChe** [comment]
如果是国人，建议使用中文交流😟

**Comment by AbelChe** [comment]
你提的建议我读不太懂，我理解你提出有两点：
1. 增加从文件读取代理的功能
2. 增加使用认证代理的功能

因为目前程序收集代理的目标是无认证的，所以暂时不会考虑需要认证的代理节点
然后从本地文件读取代理地址这个功能在TODO里了，过两天就更新了

还有就是因为这个项目的socks代理是依赖fast-socks5项目的，这个项目仅支持了socks4a(client)和socks5代理，所以http代理暂时无法实现

**Comment by passwa11** [comment]
Your understanding of this issue is correct !
